aws_access_key_id: ENC[AES256_GCM,data:r2aFzzmHZ1E4IAJZUJtf1qJ9y88=,iv:rJ51KwlkfCbdJIQWv4uRrhl5vHmkecOirpwIt5rGXfQ=,tag:4KsgDeNwFEfjDGLGEBNj+A==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:+hl6Lr219msE9p/yNbscC4Exy/gkVbOMW1sssEirn3/ot4wKidhf4N2Q,iv:PGKOa8XZPwej272NDjsMiUjqFGZiZFFo/TgPreCuiGk=,tag:tpQSITxu0lu40HqzpHSaDw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-10-09T21:56:52Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgG0CsihNkSWMPuKbx40fF+uAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDfOXTv5yKOankTtHAgEQgDxWZuXhojbZs6tEf6QSlHKP7mUJ8aYNqELVp8yTOfdpJJBbxFHgqGGeoPgS1QdcOvlJAm7AwTHqNA9bHwI=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-10-09T21:56:52Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAFVykL2vJctA+BGxwbXDZFQAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSSRRpN7a6kHLaYkdAgEQgDzMEqQE95pPqzmLJ2EmI9H0a9xaFwOOzSwOf/y42adpc8bgrj4UCVWXAEBbwTsZ7wNP+MuOWa1aTatySfo=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1kqcdx46gv7stajxenms5t83af8huc39qe450kzen55sk3kg4fdaqek48m0
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZjVvRS96NUR3T3dQVnFv
                dWFCampzUVFlM1pSQ0wyWExYRll5bkYwU3cwCjdSZHJPVjJPWU1YU2RUTHlWOUx1
                b3dKR2VKVW1hbUkyeDJUdVl6dWR6T0kKLS0tIFArL1AwWGJZOEVjQWFsaDU0VFk0
                QzBFbll6M1E4YldQVnZHcFIrWjIybUEK+FI/pR2PAwYTvVbEme78o/LYXvPgPez9
                GJ9ST+jETsclSUzQeD9pGiQ1ojLA5RQ5zR0jCbRo0ds/ySKzy3KbIDo=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-10T01:32:59Z"
    mac: ENC[AES256_GCM,data:wujNkKROP+CCTi7IT+kl8w5pJ8F+TfQ9QkR4Uu1eblfXPGhaalsUgWY/pGMdRkaMpl41tnaL0DY3Jyu9oi+nFAcSnANAC1GD2rrGGpNhsaf6XMXy7b+8jPJIsE2i8kwsnBJhjH9HdC/Uk/doWTbHRWlfdH6m3W8sJnudkqolASo=,iv:GIOCbUY92SlweglPzHP0uzUkJtuVvI3x58HK6eqiwVQ=,tag:0Mk2fW9/EMcQJ45+nRiOpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
