name: ENC[AES256_GCM,data:W7RiGgc=,iv:ZYyCTN7S+NjUGLqTt5HvfzPFaAyjzkdDYczgXkyFiJg=,tag:9bio0Ldur84Rds0bpF5giA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2024-01-11T00:15:14Z"
              enc: AQICAHhBsng+tWVe1Mv0U0sikrzXTAeU5vDmBIlzXVtLzre6hAEG4ashp3+x5PcYcPvMrz51AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhAZ+rcD770KbLEKKAgEQgDwWpBL3kD0QJ0ibNGMi294Dp58pL7mXpQzwN9JdRr9DYgn1Nlvmw0NMWk1KY/P7aclp9O3BUrUJ87KQ9go=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2024-01-11T00:15:14Z"
              enc: AQICAHgjp3NH/fcWsRZvU553ObtYuzVDG0JrFvNVTTdFYZHA2wF5g85OJmZzeUCqubcr4YOmAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXzz+FKXnQfN1vyi7AgEQgDy2fuwoDqixEPYBtB0DOE1rKAkYutGseutlDtH5nPSAzt0YGDrmSoijxN6UD0ylaxCnoNv8sUgeqAGWp1s=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSUM1TXVBeVc1OW5DeHkx
                ekZManE5amhwblBJb1BwSlVtb0doMzQ0YlQ0CnBlaUJHMDRwNzNaY0QxYXBMdXZO
                djFMTVBIVzhJUzdpanZHeVB3UU5oYnMKLS0tIHRNUG9BTi9KZmZ1WUtLaGJNUVRK
                a2NKQ2dyOUMvQWlUQm9oZVlPOHR4cjQK73TpZAVUq9qG9bSy6FYNfHYhN3cTYp0R
                S3nqqTGspFcadJ1QiRkvIzJGoVbjwGyYIiW0ThPvIBucD6I7LA3KGwQ=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2024-01-11T00:15:14Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA7iiF2iAI6a2AQ//Z1rCKxq1n4dyhdFI7HdX3iIsSKRWGonkIttXnPa96tVp
                YrAs2Gqe/X8vdYSC45skLVObDF9/wqXsv1w6neTcRchg/frStC1pR97NDk+mpdZk
                Yx8ZqqL1nrYE1e+MAtHgWoI2+kZ9OcwaX1ecbsp95a3od+2UnjdKIvok207hqi6G
                /aryNXlTD8K+GTSGc4+F8jn5qETbw7uovCVV9xdfThN5xUCgUkLgr4A1JmL0txQX
                kMuIzi5Qd8BomE4Xk+taDMwt/5exAg3xVlddabB0i3Xe2SbWXSQ7dTyZpnqhUIRD
                xVX+E1dmYiNt0zDnedfLUcwSJcV9QeIlqync46ZQT2orJTdcetpsyczOFrV8QdLE
                35g0uol5BBoRU2CXuEAYLXuwgmsQ8pUCKhXF09Y+vh2dnPAFalAYD1k9YiSt2h9B
                BL/jT2FRnktHyLW5Lm+UqZ8IozRbVadj2gRL2x7k3rIsFyBti9IQFnvHU7C4xH3n
                kG6h1frOKnG9/9edcdRYtuwTh8B7cEs8i+0mfDBlc/BPgtsfIr2ppzxESMpBZmQC
                sA5S0JxohmdhaV34Wa+hhfYRXjC5xUhLpaUgYO8jn4lCr2mTk9R4D/EIjriJ728z
                P00jiva0BsyEWsHP79fx4OtRBXqsddR6Z9nt8O1mxCm/7oj3yRU5Y86ZsyMwohTS
                XwGo6aBXwVD+0giIesJJAzsKbp3NWkpvDsdstJmA0LOKKrazlU+v3X0n3E43iZRG
                qgA5/9ORQXWOalsuk44Ubw3RHp6C+WfqzPiq3C7TgVAwiCcnknXqlLq54mDWU0L3
                =iMe0
                -----END PGP MESSAGE-----
              fp: FBBDA26E7AE5023C66D98453A93F3127586BD012
            - created_at: "2024-01-11T00:15:14Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ//XjriEJFQfkIxIBoY9WzgSBeTuJFIB9U/0eA5qSoBdyXU
                UC2ZgAGKu+zbYZ/gLJPKqvqDcUC9h2zd3BrNtjs+I0LEsfHEPChCDAhNu4mDxGuz
                iw+9Qldlj9qQ2iKif18a0TrawgUT9oUGu1Nf/2IwOjhk0FmjUHqp3v0TB97KC0yF
                S2aZCfd5QVIldF4zJUxosp/STusjRL9Avmwr+PMLqm7jQK6gjUO27xh3QprrcHrJ
                H4CNNr1DoqaMXLriXO4/4Rq41SPV/ewfkbq2eTcLMZPf7hcOpoYruJZN811duLe3
                f0ngH0qja+ng75Xa+q8VzmvcSFVRgB5uMWYcQ4JArvGtYjPsQk0TJSw56DUF55Ti
                PIDgSV2FffOc8fiZmKtEHPd4urnM2JwzUId7e1ZAuQ3vhoU04ZIMqJXCfXBfSz6X
                IyA8n6n7Wzu8dYpbbSx2Oj1i6Xb0naqUjXhNhSxmBlZoVMqjUehjqsPlqYYnR8uL
                jkWZU47iOLtrixsAfj+Y/oJOatuT4dUfHnku2UhmBd6vD4mY+UEHJJZbtacaS1hL
                o5h9NfyzE6cT0loY+w7OwhfTnkkYvI8bDfi2xPrCvNXYTq7xOwNNvdqzZT5WRsEu
                Xh+XyyuztpmjvIoJaZnPV3XqYXmk0CipRPIoCyyJIBJM1PVRMNEU/vIP1LeatxPS
                XwG6Y1majMXg/3yGcEq2Z0iqOwh50/CkW6V5wFButvmrUzKrDTeWuYMOx9Vf0LBj
                ipauxJQ3dbCB/QDrVhK0bRsOFp6Rjkm7FsCsdszK2TszDdzsmcCD9bKQGo60Oue5
                =8xUc
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-11T00:15:15Z"
    mac: ENC[AES256_GCM,data:JvhnwjCJ4OWOg0fHlMsQpPwY3Z+63XIa+EO+PkZKOtDKhMnPnCbPtRQMPv/DzEk1mIEH6vyR0stg+eEpQzKkiYGTzVYVmil7LUuLr98yhROM3K0LZ2jhzpUMYpIpUd8YKjRSLb+1MNnmsAMTnymbisZYHLjbd68cbTL+k5WCfpM=,iv:R4YaWa14i5tI4hVoAZYnuZBoECO1EhHrjCeaivfLTgc=,tag:MH/fEvNvApjjb30BYWhvbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
