APPLICATION_SERVICE_API_KEY: ENC[AES256_GCM,data:qZ93NK9VaXCN1YyzD7mQZ3J1ITftPA/0xlqvnLvbPGsHeFit,iv:cWPQSjaaqgpaf73ToNwb2A/3EzkEf96xZpflz7wExtE=,tag:aNvIjCpCDijIcOg0gy+24Q==,type:str]
apolloKey: ENC[AES256_GCM,data:AQ9zhneB49r2KosfdeRta6J08F7S0RvJTX0SRi3XS565umAjEDbiQr0Nc4C5UE0jl2v7I9hkSI2BdoGX8Ma6Rx0=,iv:RG66qYYB7vTvJT4CN2MJTyCxJorcTMPJSkGdS3R3+bI=,tag:JIxwQC2SNHP/VRPMY8WKVg==,type:str]
database_host: ENC[AES256_GCM,data:qx0lqV3j0uxypk0PVvfKfWT/KxyHNpJgNiIEDMQULl6png==,iv:xPj4NmI6cPylfy4VUQBg3BxbKx9LmwRmwH4UeDtR41g=,tag:4ihiWTANigOxIgab1XczZg==,type:str]
database_name: ENC[AES256_GCM,data:vuB/LTkY+/0GtBUyUk/ONcW+SbKiWs8mlndch+4e8Ig=,iv:HCdvYJ9SepA7T6PU4NXe585Ld7SGbwHAlUVQjApu05c=,tag:nM1Urc2S7HssS6d17buk2Q==,type:str]
database_password: ENC[AES256_GCM,data:ywZK4nBR0aU7D+zce8b22g==,iv:jRMGU5s1xww4hxdl+CgKH5G1um70FZRTQ/aaxWZLfRI=,tag:jgn2QsKqe+SHngEQMAjAWw==,type:str]
database_username: ENC[AES256_GCM,data:I/G0Crx1uNX6oLUQ083k3/UzrQFyVJM53vH26E1zI8c=,iv:IF0SpRG4ts2rFrahUlPUwoC9CXazwjQzb1ykvqOP6Jk=,tag:cWfuq/p8TXizOyYsbnzrDA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2024-01-11T17:25:36Z"
              enc: AQICAHhBsng+tWVe1Mv0U0sikrzXTAeU5vDmBIlzXVtLzre6hAGwcjNULP5k9sDonQKs7z/oAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQBuUiXiEWW5XgbbxAgEQgDyoc9PbSowNo+TQjo7rbr0QMIG8XCVUQzxenk4RGOwXCfhv+FrHXe0e9ZiOPI/N7rN5YV9wZukV+fEoH5s=
              aws_profile: ""
            - arn: arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080
              context:
                account: vault-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2024-01-11T17:25:36Z"
              enc: AQICAHiEsHN2KWLjq7r0g6mME1L4oiVPa8isyGCUEYq2v5VVQwHJrivAMKBDnYn4ZGWCCKtxAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNUXLeMSm3//i/+LPAgEQgDy/OvJdM1ZUrxYDDsjiAt6O6aW5GGNXaAdi7xpLppQcnzKsZwpqohM10YMT8TDBwV4ceGHkRmqCdMdsUOk=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2024-01-11T17:25:36Z"
              enc: AQICAHgjp3NH/fcWsRZvU553ObtYuzVDG0JrFvNVTTdFYZHA2wFebS+Iz5PkrrLSxWnAvO/FAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcMfpSm9AsZ1CpMBlAgEQgDz+jCTgV+wNmrlUyWCia4p1Fv6b0MGTH/eEkXd8ktbzdny6HcRFvfE65c64E7htKrYzr+NHHBUF+rSwBf0=
              aws_profile: ""
            - arn: arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72
              context:
                account: vault-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2024-01-11T17:25:36Z"
              enc: AQICAHhJ8zkwqzDp5MOD8o/wGzsiczV/OxQX88VXoXwaZvbxUwHf3kzef9SkbIPpmnc9WD9aAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPgIea+Cy6OC04VLRAgEQgDyl1rhNiMrefx4c+9NN3/H8JIUDvvE5ivorc1HFas9+qD/usx2qEQjCsv08DPh4fWvdMpbtnycneqjntz4=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-11T17:25:37Z"
    mac: ENC[AES256_GCM,data:DDyQpPbXf5n5bw0CcDe54COI/Fad3P7EvQHwADxq6lSKZFJB/D7tZAIQqcpHpb+X++ePc32/vU08jal3v2rq/sxwkUnczNa4aHMJSsZiGM1YEQPIAwBOADldzVYYPgSOxXHqFbZ0UqL6EczeOqfi7R6MjJM73Gb5wV32JE219jg=,iv:PO0CLWXXN77eHgvE6qU/qVaIJz12T0FtqUBktP+g1b8=,tag:7ixpJqZ36f6vzzFnc1zFew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
