environment: ENC[AES256_GCM,data:aB+BpdHZOg==,iv:lmiotWFvJdKYA7dEHYXUw8QkyRe+RuR5OX9+X1+Jnss=,tag:D+dER+qlKQy8mxu+jGBV8Q==,type:str]
newRelicKey: ENC[AES256_GCM,data:dwkKBhqZeZOFuHBKAuqqno2ZToqTHaR+bESG4nWOLacCZ/sBUHoJiQ==,iv:Id7SFwRLvvRLHQFO6w0TQGy0EISeQVBV+shRV4W8hBg=,tag:/hklqseHKaQksxHnxg/XCg==,type:str]
datadogApiKey: ENC[AES256_GCM,data:38y2DSQz/AnD/oW0EZBFXlACQgYSmS2F4b0EjRe/FiA=,iv:5pJbZ+N4RLBALjVgwbTHM6tdjlDrILhXrs+2xObTgv4=,tag:AlwzhZaEB6XNvSz50RHG/g==,type:str]
S2S_KEY_PLATFORM_AUDIT: ENC[AES256_GCM,data:99VPoa0CBPZIzdTMrIRnIfWbvVNR76YnBiwRPwf2QDgOYebdPFtpRlffc5U=,iv:kxVG5IEyE35ELdF8UiekBkVXTunaXEiVxJpywtbhYAo=,tag:ty4wk7O+ijHbeardjZcgmQ==,type:str]
servicing_redis_cluster_access_user: ENC[AES256_GCM,data:7Uek180gvJEr9JzjKLA0EIXwUcFdIEBo,iv:EpKoLcL1lICG79LY9qCNDgCvlVeGUcDAHtaNtjqK6bY=,tag:squwncAywng99+bVAeHtpQ==,type:str]
servicing_redis_cluster_access_pass: ENC[AES256_GCM,data:QMjcrfoaf/yIuIjoA0MlBI6rCW2NFdEGBTKECrPZk6s=,iv:yH0HuKAkkrJ3ydykVKgIaMEFNOQoGiHuWOJZE9SPf5Y=,tag:Chic3CkrYDPqPSw1oHzTFw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-10-26T17:37:39Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wG7w8VzhqUe/Lg3PRnvHz59AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMurQ7JfSeoZ8Lr1VAAgEQgDzd4zQNfmXjNPiDOuTs/Hv1iiTO4ChsJ7fvH51GF8Cq96mUi90UTi0kOgD+0bW97De6+SAgz1KlHvBRCoI=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-10-26T17:37:39Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgEnhccI3GsSRCElqHw4govhAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1M+bX+L1VAz9PusLAgEQgDzHP9vXDNtPVzGxkjuJvpjGuoe6CTNTkLmaoBmNbL2BKc6QdwPNJyRSqrq+kdPRY86tD60X4SXhHId0c8A=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1kqcdx46gv7stajxenms5t83af8huc39qe450kzen55sk3kg4fdaqek48m0
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRTlTNG14Y1N4YTBPYmJR
                MXZzbE5rRHJsaGxvVGlhUVNPNkhYbGREaG13CnI4d0lkTUlUMmRuRTlRcVI5c2Zl
                cm04L2JzTkRIb054bDdlVkI3ZEsrZkEKLS0tIDlJLzNRSGdpVURkemM5S1ExQlBr
                L2hLempqekxnQnhNU1NJVzNZd1ltdVkKxLfDVzH3q/D2fha1JjYyR1mXuHItZmP1
                okneLN9heVkGVQnMRr5ts8ytcuMIShqMo5qxil63jBWHFqs35krpXx4=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-26T17:37:40Z"
    mac: ENC[AES256_GCM,data:5vuj9w3HRn67wiAz8zEp/eNuweEp8e1qTfAYuTF1zLDYuQWQLTa2ElTmWF3BMMKwQp1oAV8ud9+/Ockb9XLCLjNnVBcg1irAA04/XiUSbIMQ+kkUJbdgcWNFFnnIIGxCvJYfOkQLQstwOnAMnNVAmiKI82Q0bE1eFXtQ3eLdAXw=,iv:VyGLTyHrQL3T0qZi/lW9UJUrhte1AJ24SZV6oR5VKO4=,tag:Fd10KP+9gpWXltq9nuf2oA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
