aws_access_key_id: ENC[AES256_GCM,data:9AA5hUe/KUpMS/JHCIZUjii6jGQ=,iv:xnl77Kz7cf1lHLUONR6GsdPxw5qZqU8prb8+VSXHPO8=,tag:YlAHBT8QxTBLwIh0oiT+sg==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:qKLHv/GPxSRkCFeW7JESbfzNJ0r7C3eFq/CEBFaknPuhDxtA4G+OBw==,iv:lGRQlqhfVFdyyWH5f/ShF6oM/sOVcANqNsweW+qQkw0=,tag:d37QzGXnzduCuGJ9px/F0g==,type:str]
output: ENC[AES256_GCM,data:n8efIw==,iv:ez7Gqks3cZ8YO+DGtna8CC5VMgFmnbe9TIdeFdrUXZg=,tag:QnbCDb6g0X0pc0gKKqZzEA==,type:str]
region: ENC[AES256_GCM,data:8dJV1fNyohue,iv:ebuu6W5dRYJtpNiPP+tLDHOggDAOZWc2Wqr/6JslRBM=,tag:461xzAlbgw7BIF/tAUSfXg==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27
              context:
                account: sops-sa
                type: age-master-key
              created_at: "2023-10-07T08:39:36Z"
              enc: AQICAHhBsng+tWVe1Mv0U0sikrzXTAeU5vDmBIlzXVtLzre6hAH27nBfn3xoUy9hTnFSDhY7AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXlm0yLFUxAS6dP5KAgEQgDzYaHDZxfwOq8mI2NKlKGb+1rbdXTEZqokGot497C4LbK39pfHqVfxjKiuy/IHH+kF05KOzh9f0TmjYbwg=
              aws_profile: ""
            - arn: arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080
              context:
                account: default
                type: age-master-key
              created_at: "2023-10-07T08:39:36Z"
              enc: AQICAHiEsHN2KWLjq7r0g6mME1L4oiVPa8isyGCUEYq2v5VVQwE0ogxRxeBkYBQMCBhk4ZbiAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXAJID9/d8oQKsU/UAgEQgDwXf3Lfxe8Pse6AefJhnCMUfZI0c01OO1mWmAPGyof9v8zBDo0vYyvedwjc7CuHNXb688iad3VLGkx9lWM=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998
              context:
                account: sops-sa
                type: age-master-key
              created_at: "2023-10-07T08:39:36Z"
              enc: AQICAHgjp3NH/fcWsRZvU553ObtYuzVDG0JrFvNVTTdFYZHA2wF3pwMMqTvX9L05a9Lvfu7sAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCVnk1+nRaF4t2ZE+AgEQgDx1/iOsE5lHtaYVRVzNpUbNiREY58Gze1akz1aOZKlc8YsyEl0vfxiGnHBNiehNzBevBpGV4AS7amT4C28=
              aws_profile: ""
            - arn: arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72
              context:
                account: default
                type: age-master-key
              created_at: "2023-10-07T08:39:36Z"
              enc: AQICAHhJ8zkwqzDp5MOD8o/wGzsiczV/OxQX88VXoXwaZvbxUwF9kiqvUNgCMkDxbXXt5qiCAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqOn8FjEYTg8P2xv5AgEQgDw0RKklHyEwBWMEn6leBWv3FVp3kRgWfv4XU+VNXfzNZmNKn0oa7yBUiIru1LMWx08/rWUxM2mxT5kgm/A=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1kqcdx46gv7stajxenms5t83af8huc39qe450kzen55sk3kg4fdaqek48m0
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaWJYQ2s2aVBMeXc3b05L
                eTlzVVYwK0ZFTVRxZ0pGZzI2cDdXbjdkSGpVCjc3eXRMZU1ndDdGeVl3TFFaRVBN
                aXgwWEV1Ym95WlRkWG5OMXNuZWx0WkkKLS0tIEorVTZhTmdwbVRTa3FGK2cwYjBm
                NkcrL1FVSGVLcTlxak1FT2drb1RRdnMKgo4aVFrd8NSYBTSEtAw5+9amHGXs+nbQ
                a9WbAzDPZQY3yTGjhtqobOCb216fJtG2Ojo+EKSMhPPvK4kSG67g/RM=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-07T08:39:37Z"
    mac: ENC[AES256_GCM,data:uCJ3gd85zM6Yukusl3hIajz/myhUlGL87EizHjzWDxT/NQa5JdQbr0t7diS4Y3WUW/HUH/lYkKTmbBB83GKxKftITOaDwZlhz9Xz5mttpdyTZzIXaSR6ed8qo+d8NqiQDaU4THIU0v82g3kUigCVpxzdE5jpBC4GERh3OX8nCCM=,iv:2sdgQ2SSiauhljmC7EfnWIju7dhc7tntlHDDAOCNJxI=,tag:h6hirx8LsJxij8XFokZ+4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
