ACCESS_KEYS: ENC[AES256_GCM,data:57KhgJI2IXd2dTi8U8VN5hs8LNKxGBYVjOdK+MrHQ+DpkhSFPiQCNXeVIy9QZIIyEi/9Kav5NpL0wgDVphgUM1ktfLozGpWVMA==,iv:PfSW8zajn/r/tMfy9KxgpJRgfEJ2p6xHcD/umo7rWx4=,tag:aOstZcpbyU5I10IeL9ER9Q==,type:str]
SIGNING_KEY: ENC[AES256_GCM,data:UqsIPdCXMyHUDVyfK+ablna5kgxhEP8gm1Ze7ESMTbtaOvQh,iv:HiJl+yaGQHWS9C0y2Irhcm8XgAQ6yYlzH+0JB02PKJs=,tag:YVqvPb7HBz97449w1OCvVg==,type:str]
database_host: ENC[AES256_GCM,data:sHmtzEVA7mlT35EFOPEFIr9m2yveZAAw6kbSo3tZhWSLhQ==,iv:obLp9C/xF06NgiDSQoeQGJtV3xhAzgriJNo3CyEK/84=,tag:MS1ymOD0TW0dAh5Ak8lYkg==,type:str]
database_name: ENC[AES256_GCM,data:48yp2KBRILtEZ0KJGhdnR7IFem+E9ConoQ==,iv:fXAEHE9HHk6vC+PD8s66g/oAh9FS8NIV36PYkTbIKQE=,tag:UfdvUD8RIDjhwe5o0OqV/Q==,type:str]
database_password: ENC[AES256_GCM,data:PQ9gD041U4od2vQibKNC5Q==,iv:W5k9KqMZLnlD5yBViN/PxDMpXSozAZOJgIsYg83LeC8=,tag:FBRnpyWaMPqP+w+OX6l2Xg==,type:str]
database_username: ENC[AES256_GCM,data:vigpbk1sEdjNy22bIjbWS+KHXg7B3+XdcA==,iv:QbyokRnzaw682/ci1KLFUmiDn6zF4xn5VBLPVpCtIUI=,tag:aNgxw8zAJi3cxgKAc5INXA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-13T03:22:50Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wHX/rqPXVrrea3fyEciugYjAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvZxzWXr4tbTLgOU4AgEQgDxXHBARBkcx0Qjt4hvVS40L6aPCdpdj6Z7F/KPMMHtRW3od2P2MiIoIDRyw8ERdw06syrEiyIK/48QRr4E=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-13T03:22:50Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgGLR+svZuf18ILI+BKMKWuCAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTQdD6oxa/xHUDW7QAgEQgDwKlxIH7mQl3WyEulZkLFwd+gXl++k/qP1aYb2mDrduRatTLCAG/KJiCsFcIoPwNVLJHlhnqO1eSLPsueM=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:22:51Z"
    mac: ENC[AES256_GCM,data:ttclqjhfDmLVnFGEwwWqq4pX32FxY9zdvrGgBVUdZVkOglXLe826GGYcqLlTiuBE+pSLneVRoZDz4LBMTbhliufB87XxsTsLrm0+cMhhucdqRARWZsdRU/lGvYkrofo4864VmYXXwam44N8xEcBF8HioFQEYn2NqQQSA/S7QMKs=,iv:PDgw0WfQf/hhCcFWYokP1C9FEL8zs2r+ebYT0aAux68=,tag:LHjJfCP9JPKVEUTS/5qS1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
