APPLICATION_SERVICE_API_KEY: ENC[AES256_GCM,data:JX+awUfuYXIZ6dRGQqWqCK75nKcWzg6j00Wyr1eKUFFwfOJo,iv:79dg1fwSjaFrYIQyhu4x7nGcqJBHE/Xrhtbn097imOE=,tag:km8M/d3WBtbZVZjT5WGBnQ==,type:str]
apolloKey: ENC[AES256_GCM,data:tSEGn8NGWi8C2G9ppzxBQST5SNbWwuP/i5gJSocZhPmNWK6hnfyrH6XXFOtLCr347KsFvtJ8rGPopKSx1D4IMY8=,iv:KuUKByZ6ItodkZxPY/Mk8gkOuOZ1fD6LQSTwU866ljI=,tag:Ih6H94bSL0VC4Rqx96ge8g==,type:str]
database_host: ENC[AES256_GCM,data:SmKuY3GXnAgDhgYqJrBGdN9zClNSjdOyTY2bBSjX1U2w4A==,iv:vpqpkF3WFIWN/n7Z9iryyjEF5AQ1Zx/sVLfBTTzYKhU=,tag:1sLZqnMzjX1H2+biC29xcw==,type:str]
database_name: ENC[AES256_GCM,data:Yd3eoHTxCmve2tF2wzY12QC1kk9dCteoSFUniPXVyjY=,iv:1Br7u3k2iq8FMFcDo5SzRQq7qEje/fioNSwcILTqSf4=,tag:6iE3m62vG8cWyvqreqUHqA==,type:str]
database_password: ENC[AES256_GCM,data:bPd1xJsoi2LvqN6WfH4Riw==,iv:JjxvAlU44SiFvwmDzonlKlBRKCLUIt1S0wPN+0lXO7w=,tag:T1JGxhLbJXfV5Icx1dlBwg==,type:str]
database_username: ENC[AES256_GCM,data:xcrCkgC2kljqwJeVg11IMxmrFzZIPEjBLJmkxEeU0EQ=,iv:je72EtmwnHnax0ufu+Dk9XfCKm45ApXm7FvLggFvnHw=,tag:+2epTV/IFu6SDbFDItcpeA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-13T03:22:48Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wH+2fuJEKv6RcpvB8+nFJyuAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMk6y41IsmFrysM/9aAgEQgDxEpi3pBchQdZDVZEbwAAPJxQ8+C5uNFFkjC+T0NE0dRT6JY/zOpx0cj8IQf/7y0GzbmMxzoQpzaODlr68=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-13T03:22:48Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgGl+NuL7bWfTk6g4rPgWyulAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNlvhFqK6mKzOD9aMAgEQgDwOaFta54ZJ/d6raJYF3kTpoGwdn4VpyRFFw5TO4XP6ko3fEGs5cHYhwEVCgqG8sJR+5uhqevNUi3t1li0=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:22:48Z"
    mac: ENC[AES256_GCM,data:wy5AVv1OIk84ev3PACw/QdkgpZ55Lrjb4aKqyNoMwUPj4vouRTXmrQ0WWQl4a8O5FXiyCR5X6r2uUOTlSFHWstu12KsRX5SY4IpYqN+aqC8zfmci5J6rhKo8NiNjE3Xz4D9ExAhSQO6wIgJzA4zvmTMWKi1CGFJvJSauLkz9gAk=,iv:V2MH1Wb2pDICAR+LM1nyuEySl+Nb9VYLJEV9ryKiE18=,tag:5/qq90VM4k4oSJSusb47+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
