ACCESS_KEYS: ENC[AES256_GCM,data:57KhgJI2IXd2dTi8U8VN5hs8LNKxGBYVjOdK+MrHQ+DpkhSFPiQCNXeVIy9QZIIyEi/9Kav5NpL0wgDVphgUM1ktfLozGpWVMA==,iv:PfSW8zajn/r/tMfy9KxgpJRgfEJ2p6xHcD/umo7rWx4=,tag:aOstZcpbyU5I10IeL9ER9Q==,type:str]
SIGNING_KEY: ENC[AES256_GCM,data:UqsIPdCXMyHUDVyfK+ablna5kgxhEP8gm1Ze7ESMTbtaOvQh,iv:HiJl+yaGQHWS9C0y2Irhcm8XgAQ6yYlzH+0JB02PKJs=,tag:YVqvPb7HBz97449w1OCvVg==,type:str]
database_host: ENC[AES256_GCM,data:sHmtzEVA7mlT35EFOPEFIr9m2yveZAAw6kbSo3tZhWSLhQ==,iv:obLp9C/xF06NgiDSQoeQGJtV3xhAzgriJNo3CyEK/84=,tag:MS1ymOD0TW0dAh5Ak8lYkg==,type:str]
database_name: ENC[AES256_GCM,data:48yp2KBRILtEZ0KJGhdnR7IFem+E9ConoQ==,iv:fXAEHE9HHk6vC+PD8s66g/oAh9FS8NIV36PYkTbIKQE=,tag:UfdvUD8RIDjhwe5o0OqV/Q==,type:str]
database_password: ENC[AES256_GCM,data:PQ9gD041U4od2vQibKNC5Q==,iv:W5k9KqMZLnlD5yBViN/PxDMpXSozAZOJgIsYg83LeC8=,tag:FBRnpyWaMPqP+w+OX6l2Xg==,type:str]
database_username: ENC[AES256_GCM,data:vigpbk1sEdjNy22bIjbWS+KHXg7B3+XdcA==,iv:QbyokRnzaw682/ci1KLFUmiDn6zF4xn5VBLPVpCtIUI=,tag:aNgxw8zAJi3cxgKAc5INXA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-15T23:15:00Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wF8gd264wjoBwqIWORsBFL5AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEDRK4dvVReiDb5t0AgEQgDxGgiWvar57WQIu7YJZVDfWmkZu83nMOtJPP9a8xBn1/PCwS4VDJx+nnuhlDl1rXImw3sCRjb9qNfLWOHk=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-15T23:15:00Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgEkmgASMrydfn3bPr6XRdZVAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb6ZlfPBGOug5pnwZAgEQgDyCyOsUxCKu5xb7TpW2g5zgUY8A/HHZ2+58oNWUrW2UbHCO8AwCg6xAtSlPGN5nLzA2RIW888l2MFiMQSw=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRGFpQVFJUXgvQzR6TjF1
                OGhyRDZObjRpejlwZEgxTjRyL0wwU0tVWUVjCmEyYjRZVE1YelFKUklHWUIwVzlH
                bUFlS3AyekVJSG53SkQwd0EyQ2xMc3cKLS0tIG5OR2RXbmRscFJ1SWRIUDcrUGsr
                OEdmS1ZrMmRMQ3N6amJxUzhXUDNyZ2MKV4XNG4v0Pkb12lkGcd506RmrsozUgGCg
                k2Mw7ReH2mxsnarCFhciAbgXLN68J3v6dFuGCLa42ss9IBRKOgF5ig4=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-15T23:15:00Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA1mTlAlnuwDYAQ//SIHxVUduFNZ5ZjHDfzDjPwx3XMakGhODHKrgb+tE5jPU
                o7nszfB+DGxLbks51N1MBk1sbHwGdQFAVKYAdJRtm35habqqzTzTt70ElzShM1pd
                pPHeVr3LczYZit6H4QzH5vIfokCLxpto3jqfjxs4IVF/49+v76YAnK25lFKBWvcz
                nELYJaE8RrH/Mzv9oga6GXEejxOyYeJct9ufY+ePmZATxkoB5Qhmxnq+Nmalk24F
                g2TToi7EZl6jIkc8L2nglXes41GFQRf3bvmfrOJEMXLvtvm9rwo/9o+9cF/zTh4l
                DTGspc2/tkOWgy9sn1XKN6uz799EH9xUl8MflXVXnap52DQPxUwoGST64wep+Fwv
                kwiGf5MrVScwVv38pZHGNRVN75OCWeM9KHMm2A5LNvsQlZUBRoVU+ahNwMdeEvgh
                3uSbTJRMNwlejsmgBbYaZeV++bsdC20jABQfthpxJz495Ms9yYFeoDxkpD0XVITw
                zC7EjzFKAJ1vXb8SVlxbyAPf/oDmAhOS1g7+N7sGJ+8tZlrN2NdCBwJxvkYil35V
                y7hJz5j0v81u3xD8Phpvnumb+BR26hXG6HaOTQX17J8YyIjeBPaihdviDUS6pLr1
                oWFLkhl6IEQBzFOOghSe7+61ESXZnO64w/6JdUPfOVpjo3CBYhQIpy6+Z4BZfmrS
                XwEMOOC1QAOjizMZrhidefJgidAGizGQzKNUvxrbLG4Sz9v7zzFDSWyDItpd4L37
                X673qKkJtxoAxJIeVSDPugzFsMjWottFil7Xah/ikoEQHHnsp15j5mDCCkE5B/sx
                =TYYp
                -----END PGP MESSAGE-----
              fp: 7246137C29494AB51DB9DC75A503AED1209A6985
            - created_at: "2023-12-15T23:15:00Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ/+KEZXyPVWLZBgeOqCvm6zSTGWWuQZvExZzD9l03ritJkP
                2MXSi26g+7oqDrnNRTCKhJapWrAESG2WMc7qmubADy2h+u+kE58UjPeAtSqKeB1L
                Hmz+qf+ya30+/ofzleZFXMzbHb8eDgSIULtP4M2C0HPH7LPSSLeQcXJnTByBerKW
                nEC7ti4HUKhTzSVprwzAy8hLSWY2Os1g7m7tvYvWuM30RTEWiQnuQHV2hpPCGUOi
                /q7oSM1oeIehEHF6eMD0Pqb7w4jmJM6FBrNg0htT41q+W0OfqlD7VaCHoI+fbHCF
                g5d1YBd8sYQ6qqpi2ccQnN3Plu5IQBJYZXA5C1v6UFgCS5HHLjyDcbPV7Q8zz8Fo
                Q8GSgeRfBgLZqAvooXQfyOAn3k6Yxz12MxmHsVdbW9PPolr54/twCCTFK1+YVO2R
                BqwPOu7PJC4uw2hx1XBZLsmj0X+GfJh2o0JsASfbE7fNsXD5OMlp2JwU6KPXcQX0
                zQ+ILxpadoPhKdK+PtkA+bJ2/lC/NdGnhH0FskXQa78FzHtwWeO2ft+gwnNNRwxc
                kbapOJVjuBJNLzMDe7IWC8OxqsfHltrquZGuYAX3xbykWzFLWOf7X35IhV1QPz6z
                gAmqQ9E9fGE8C8d61N43cq7DqUbNNtkxhnA6an1vuUn6VlvdmkS2umlVKlMIAhrS
                XwHtLcpxR+v04Zo6BV4m6ciYG3KrO5fkiHFl8LiqbV4MUHD4THAHYERWF3ztnCgW
                cgXB1IJFYRyb0Muysy/wGl3SMh/JZ4JwwPAduqV69yJkGiaRlYmHmy1YSIldEBfI
                =jHWB
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:22:51Z"
    mac: ENC[AES256_GCM,data:ttclqjhfDmLVnFGEwwWqq4pX32FxY9zdvrGgBVUdZVkOglXLe826GGYcqLlTiuBE+pSLneVRoZDz4LBMTbhliufB87XxsTsLrm0+cMhhucdqRARWZsdRU/lGvYkrofo4864VmYXXwam44N8xEcBF8HioFQEYn2NqQQSA/S7QMKs=,iv:PDgw0WfQf/hhCcFWYokP1C9FEL8zs2r+ebYT0aAux68=,tag:LHjJfCP9JPKVEUTS/5qS1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
