database_host: ENC[AES256_GCM,data:4g+UeHNHuLHZyViwlzDAmFTPP/YhxN3SGMk8aWBz+/8KQA==,iv:I6jiHrSqgCWWNnLlgXiGrXmKaGHv+DgpOJ4IyNxX3Z0=,tag:Pfy0CnIekbRG0Z3v9v5Ahg==,type:str]
database_name: ENC[AES256_GCM,data:ZVR0DAw/Iyo09TJP2b5ZqTIw,iv:u1/y/PYnyhgayIMxrjB9dcmMr/BRtUvljOWrOwlbkVo=,tag:QZGUUGXE7YN1mteVLuqfTA==,type:str]
database_password: ENC[AES256_GCM,data:Irt+x5UqyuDC0Q9u6O5S1iYx9tmbqlq2X4hdMoNTtpc=,iv:0dW+B1y+pVQfNc31ZTZKVpoyPxaoJARD+oKbxr7x9kU=,tag:8adUbeJ9Y2won1buvpwk9w==,type:str]
database_username: ENC[AES256_GCM,data:+lK8i6/sYgbZEpll+qLa+6oo56yz/kU3dGXmvtFcbg==,iv:IsvRocy05B4MUT5jrs87OUEdF4ioQjoFpHsNKdGzZ+Y=,tag:UR10wNr4sHXIps79RIxPNw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-15T23:15:19Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wH1mPdGSUDukTCt77pCCiC0AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMWgkGuTPl11XkZ5cAAgEQgDzItqCQqM7u8OdAuL5hAJP4ZORVKokQVYPCaJuVqtA9TJNgpMEd/wP1w0v4dajbqb1HJ6M7LruU39TDOAM=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-15T23:15:19Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgEw4BslELMUrzvhIXuhzHGZAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqeyUyBrm0TYCYsC6AgEQgDxMEkhOAT5HY8cEbs3wqtwTIbPRhhr+ov+ygrRsEOXEPtAnUjJcKBWnojuFDCvVDIsRti6artBhU9pXfao=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOXh4dGZPRWliVCtQM25D
                dllEbnVjek8zcjREbXlnSUZZMC9pMnRsUm5ZCkFBRU9jY0JMN2dIZ2JLUWNERWJK
                MG5wZDd4dTV6REVOVWNBaTVQMDBKL1kKLS0tIDNoZmxEdHlRY2ViL0dOYTVJU0pu
                SWRzK2FlV2l5clVEZU8xRWpDWjl2eWsK0Bb9zGi5U1BrTamNRBXIBoLamQYgbZzA
                z5iQcyI02JPueMgXQ2rlmoMGYvXaTYPS7rqYuzu1NuM4NRWU0GeX1P4=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-15T23:15:19Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA1mTlAlnuwDYAQ//crLdIcl12lTO4KRhIRYYGgbHRkWQBRYk+4KQwh0BKVkt
                zH9LKGJRwuokEB2OFFi8sry9YRaHuDZtFohdvBGl8vqJ0eppMhD/GVfXgaR4lNi8
                KfGDL3Aq1s9UCxg25NZ05v1bxR8woA8JhL7h8jqDPlO57kBB1hdkRhrPJjXb/LQJ
                MrGAv0Mk602Rdr6MXwAukHy2SEPqf7aYzftoO2sF/z/Ua2ieVH0qy56/AhjGETar
                3W8D0TYhBz36AAiVMF/thSUqeXRiNZgl2TbaskOvMcUY2g8ZvDcg7CFxd2nFOHGa
                o/g+PXse3xKlGe4ptG28rpSQ0+EADlzGDlUigZIiJnrmUFErEWSuhu0fxl4CRLBy
                ZUXDQvMWYnBvt/ZhwGAcS2PmZLBCqJhXvQMBx8IPcZcfB+5zBYpZARrRQMz2pHum
                pxUVhX0RiWEXXTHxFGfURq5v5X5veODl6P15p8Nb8aDYaZLnRdp3evU4wHC/+o/T
                RaEjFn9TAwFzNlnzQnk+Sv6vQR97xHFKlpKESMEG+12/AuUf3o0Auy1e9atAyhlA
                3gWK83KClomfxgod5baV0wl4+mh3b7Ibd2M2KQX+n703hFa93+JA68CcOyPtlCiM
                GKlX5hg1But6DH9WvGuklBKN4DzToJ97Uyu9h4ATv2XoLC9UP8qUsoQX9wmPbx7S
                XwGCOC2fSkCIrF2b6d8e/zdW6/OMyhp36o7JEhlHYsKTAhnap+wEk8twjsZWQJA3
                YIpthHxrDpZdCL0epnSzzzw9sY+eh93len8Q2eUfCqpQgJALif1rVky0raoDgCc1
                =+MIQ
                -----END PGP MESSAGE-----
              fp: 7246137C29494AB51DB9DC75A503AED1209A6985
            - created_at: "2023-12-15T23:15:19Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ/+I0OGkfHnN6+TTVmRT8kpaz6YC9gRt1cOPE8Ql9Ijk/6X
                qvwp4hI8JCGHGTzL9dshdJcPqMHltaPju7VpKlBJ7/ToTuywDe+2sJME8QFmzz/n
                XnIEBUrfuJLwAI9ZjAO1PwSy7Fw4oRbw+OQoPs0xsPyZNP+pi0aAvCShjJNLeZqh
                yAESW+g5O2G//LQvBYIOtov7dT3Sg1rU93Hj9vUBaO3tmkKJ0LhF9grUUTe+aWqk
                s4VEE7GsSWf9d6b33ECPDjjrQRQ1Els+xQgHcADBmLTFrK2Vp14SSFS6FXx+3pJq
                QAmVvy0z2vaTJkykGam2mmtTFZ1ZaTFbamriasq0K5IGqVGUsq11R8IgW8Q7E2o+
                uVYFyvL4BwSjIJ0IRB3ssUeoyKd6LatGrhVEIwczNRrbyDcDyUBm4bDqWPaPP7T5
                iH59egwSFQUqKG/vksfIXh2889NucnUzb9/LaCJPW3tbk+AHcZtgiMgXW+xgFaTZ
                teuvfSJ3E/RXMNQ6yy1Vj9vi2QlwxuZC3A0tYwKmdHpbr6gpURELbmPLzlXbqCjS
                4PmSqZ+hUo/1P8GY1vc4f6HrfzYZtDHZjNqk3uZdw3++AeaFAuxT00KppgRJ/yBj
                Q1mYJ33mDSzc1ypHmADo4Je/xUgQ1A/OnEVvA30MjCcmGHTMNg8sy85b2mdcNjXS
                XwFArTxJqUvvv4yDTRkIuzB8PwaDPDmZE2VQ2udWAvbQSWXxX6SWWMHGB5rQ5AZM
                CFOhhpzMseTuK5we+gbxN648CDL1mrTa2RmGwc/zuhsBeNEQ0RcVcmbyk+Vuq0Zs
                =WIVN
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:23:11Z"
    mac: ENC[AES256_GCM,data:IIu+hduoeLaUA+dqhiZyN7OwebZFSoWI8UNjFlVSXP4DDXSbl2X+iRDusvOL48Gpk2oQmW7S0vactK7MEG2JtZRzKe1D/Rp08d1rAAlIZMD+/5E4JbC4xgvcAr9PtmKUunFAI9zUfR2RhfjJPg3xK6tJJSmn7VALMmmW+4YzNlA=,iv:uwjdFJUZ/4k6SL6x+L09YY7D9/KN6Gcsbw9aEKGLVro=,tag:G9K7m0wRcGqS8QTpuwsSpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
