database_host: ENC[AES256_GCM,data:4g+UeHNHuLHZyViwlzDAmFTPP/YhxN3SGMk8aWBz+/8KQA==,iv:I6jiHrSqgCWWNnLlgXiGrXmKaGHv+DgpOJ4IyNxX3Z0=,tag:Pfy0CnIekbRG0Z3v9v5Ahg==,type:str]
database_name: ENC[AES256_GCM,data:ZVR0DAw/Iyo09TJP2b5ZqTIw,iv:u1/y/PYnyhgayIMxrjB9dcmMr/BRtUvljOWrOwlbkVo=,tag:QZGUUGXE7YN1mteVLuqfTA==,type:str]
database_password: ENC[AES256_GCM,data:Irt+x5UqyuDC0Q9u6O5S1iYx9tmbqlq2X4hdMoNTtpc=,iv:0dW+B1y+pVQfNc31ZTZKVpoyPxaoJARD+oKbxr7x9kU=,tag:8adUbeJ9Y2won1buvpwk9w==,type:str]
database_username: ENC[AES256_GCM,data:+lK8i6/sYgbZEpll+qLa+6oo56yz/kU3dGXmvtFcbg==,iv:IsvRocy05B4MUT5jrs87OUEdF4ioQjoFpHsNKdGzZ+Y=,tag:UR10wNr4sHXIps79RIxPNw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-13T03:23:10Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wG09eE83G0NcRwa158I1fOKAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0VLnaAq/yIoWNv8BAgEQgDyejvi/jnuQeFNAkk+WCFSXi5Aps/y6jZXpKeKwPUOZnCnA09ANae/P86C/vMCPHERYZx5/almijtLS0SY=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-13T03:23:10Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgHtJtUB3qg0SsuC08edHbRHAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9wdWp7mCNj7pe6wbAgEQgDxKiTvPfKMA0XuGM+shi7VOIMaqTfDdzmi80OWc9SB6mkSUGhS1Gd6P3J2NKm7AsKifYJurA/mn5GcePrY=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:23:11Z"
    mac: ENC[AES256_GCM,data:IIu+hduoeLaUA+dqhiZyN7OwebZFSoWI8UNjFlVSXP4DDXSbl2X+iRDusvOL48Gpk2oQmW7S0vactK7MEG2JtZRzKe1D/Rp08d1rAAlIZMD+/5E4JbC4xgvcAr9PtmKUunFAI9zUfR2RhfjJPg3xK6tJJSmn7VALMmmW+4YzNlA=,iv:uwjdFJUZ/4k6SL6x+L09YY7D9/KN6Gcsbw9aEKGLVro=,tag:G9K7m0wRcGqS8QTpuwsSpQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
