environment: ENC[AES256_GCM,data:NWzE9cf/Fg==,iv:lZ+jUx+dUg8I1Cz9gvbTIe+hBCY7UGp4lY+fZ63gIZs=,tag:UFtWCgowlMK/X/2ehtbOIQ==,type:str]
newRelicKey: ENC[AES256_GCM,data:LnZUo9RwNClWEtHgrYACGMd3Qxcu++yKUiOLM3hxjzswdni8WjnbwA==,iv:YfTXiJmK4YLgPGCvnWcKiHWBof5fzKtZigEPsw+7LrM=,tag:iBMzD0B0VdcuiWjgmGYqYA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-13T03:23:45Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wHcBb8X0vnbpeOFuXJRR5AmAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDBnQFuY30ojnMUrkAgEQgDylp2TJmhJBfuoUusSSMT1AyFXMihiWPHCoKrSy3uWYjZ7POeDrNHrBdyQlcCmOdgggv1QOq2Df8lkXZC4=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-13T03:23:45Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgGeX7gzdvKXtIgV59iGqemyAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzsLWKc7H0HRaKTHfAgEQgDzSaGrIV6pd71ftWAAElXyiAR5WoJM4jqNRzFIsFnI0xIL2wVFe/CUCIiHlicFEOIwygbv23VQySKOzUm8=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:23:46Z"
    mac: ENC[AES256_GCM,data:2S4NHHOcZwl68QCbMeB2D84XLePid6rGFJmTMSqR6D+y1zp8uzLp0Di/HjrC6kd6rpP3wLRpOAESxHz6o7nobKXw3GScqiToBETyah04CE2rSL4a8ucHYpzxhslCxxLnaUqdYe+89ONNgqwcpKjdFZoQpKe/Z4FbB8P5WQchScQ=,iv:v+LpWJiFZXdFr2uQdRneh0qMu8oZkEHlD95DclAV24s=,tag:zbQknLTCDy5N9n6aEDEO9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
