ACRU_DATA_AUTH_KEY: ENC[AES256_GCM,data:G1OvMx6Vn+IA015caZ1icypbcvf0+QjFkv79I6tM9kcW6zrP,iv:0WFwXll70E2lEHb6yZDFTzdAjVn5Q0VoXPIKJ7rlZbA=,tag:D6OVsvcaiWqPKFDX37d6lQ==,type:str]
APEM_SERVICE_AUTH_KEY: ENC[AES256_GCM,data:8tpZZSv7iJ24J78Vz3h6gBJLBgTsOezo706zYv317uIcCjDi,iv:LiiEryJoFJcs7z1dXGZRqdQu0AIXbnZMU6uJmYt9/pM=,tag:jO/Gt0NZZvRBNvEwBLeSWw==,type:str]
INTERNAL_REST_AUTH: ENC[AES256_GCM,data:WdPhHMAw6Fdbqry8T/F3WPWz7Av1JHDc,iv:ymZdg1zLvUMRBR1H0g/MuyPz9Xwwau7ZUKz2yUETRoM=,tag:qSaMF1n3lN1BxanrU/wWWA==,type:str]
PL_USER_CLIENT_PROFILE_AUTH_KEY: ENC[AES256_GCM,data:cwmfSOG4cLg+sw8h0otYzwbwJi00aFMij8LCs/60Koob6mpY,iv:cCWR0nWs6dnQsTEtkCts0Ehm2XSVVEjlSndTclFQky0=,tag:/2cyylIb3ggfbxbE9opuHw==,type:str]
SLO_BASIC_USER_CONTACT_AUTH_KEY: ENC[AES256_GCM,data:DSH5+SQohhyYAf/HwyZwDsGv,iv:B8q+5JnKcb/Mm2GeHEECpHOTP4JvGhvpGBdP83mPP4I=,tag:so7j+oowT8+Nj4JdbwNaOA==,type:str]
SLO_EXTENDED_USER_CONTACT_AUTH_KEY: ENC[AES256_GCM,data:t4kwO7A2ccUK281Fz48rIw==,iv:4CvWfKVOoFVrJGSt53j3YLl0HPCZWRDeSCwy5ktlF78=,tag:BdPD3hrg9pSglTjVK9V29Q==,type:str]
SLO_SERVICE_AUTH_KEY: ENC[AES256_GCM,data:CcnYneM+w28Rot5ifLbMuDi1a+vM3fM+,iv:TvFbIKi6DODeSIAPNKeT0PUXcEg+1evvXt0gD23zx84=,tag:0Lt6ta1Yziz3EOwgVnCw0A==,type:str]
edtt_login: ENC[AES256_GCM,data:kc1i1+gvHSiwqgb/smOhlA==,iv:EwrLwUOWA9YRe9MRy0N8Er69DGf/NUwNDBb5RsD1eR4=,tag:R7ZLDM3bVtn823+qqWyF+g==,type:str]
magic_links_test_auth_token: ENC[AES256_GCM,data:SygA0bs4e8bwe8gFX7+k9Z3C7cvTf+btSW/wbNvrwMa3BmEr8wavbyYu1C8zq5AYs6Y7P/dyKx6p7fukBX3a9w==,iv:45Q8dpHZhoH+hniMBqteFfM7Q1pG9G8sGS+8K4UxXdg=,tag:Rdjx3OdwxMkHCDCzVXJVRA==,type:str]
user_service_token: ENC[AES256_GCM,data:x91PfGGLzA/5PIWgJps72eo2IBoNdkePxMQZRU8OrYxFGZhZOU6MYQJqNfcWRN3Gd0z5e4B6MZf+rYxz5j82h0DbNo1A8Uq/zDJOmRLrWbWMP/437cRxfA==,iv:UewOV+p6877nP5ur2eJy9SIZpsSX+3iFXLFFkSsk3S4=,tag:bbHj+SxV7FbHycdNopL3mQ==,type:str]
BRAZE_TOKEN: ENC[AES256_GCM,data:xfrFe8icm9Qag6t4XpY/DcnMofFqaA+pEYvqRpa/cFL/UdrB,iv:VBO7FgReLEOvGAHa/UVJzt14z1UTFepr/jWrS+9CBl8=,tag:ei0oUosZrMRtdf8VE1ckMw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2024-01-03T23:51:34Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wFao9Ett79s0985zInoqU2jAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT5hnxXm38V0zA3ENAgEQgDzlbA8jp3kihTL3RiclRB/moW1b6b2R/zUHhnvN4WE7Ti8f2iucnrfCg4HTtgBg7MFOxesycNNGz9AGaEo=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2024-01-03T23:51:34Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgGDHpgNVZwjxRIJPK82MkU8AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMa2yiT0Cx0nFFD2PjAgEQgDzUWNrqzqC3iuBtBdB7G0YTK09iVWw+Z7tPtEv7fv5mUZ/lTaibPkoe9r3gD66tX4LhqkZHNvq57FEpwec=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-03T23:51:35Z"
    mac: ENC[AES256_GCM,data:U64ixlxKml9/CLJNdpHgStT6z/wrOf6G9IosURebK9zEQEkYWWiK0UOlh665F7sLvqnLjfMTiKJ6p98ZZN7bE4coxmqOdcjHrexv9JBF1yY26FVrNH9ga+ZXk2yl6703rQtwaVNJW9Ueo76nu6z1Yl2s7XFbJnZmwsb9kvhGI4I=,iv:0qshie5X6DZ0uaRqthhim8SaeAxCgOCu7QZX4HrYR6s=,tag:W8zatADrOquNL673nJxyPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
