database_host: ENC[AES256_GCM,data:+lJDs/En8uq2PY7qC3wTjoMMeTcGekoRog==,iv:FWydqyLFyhnnEsklJhqYTPQ1Z10g61AD68yWUMJHUrw=,tag:hwcRDHkJYbZCPhDtUvLa0A==,type:str]
database_name: ENC[AES256_GCM,data:gXwp38zKXiQPfKfWSbrGXxR7yE5s,iv:qgp2dTRZ1EIl1khNwAyrFYUep3LFjlhbEWynfg8iECs=,tag:xEWuzdxlKT+coQlyaaml0Q==,type:str]
database_password: ENC[AES256_GCM,data:dxPmSYKQXQrCV2sl3edRMQ==,iv:8E0+gc36X6usa6+bZ0QvdGY9GYZ4hfmxsgb2VzPrWzU=,tag:WjQ6B4STrxoEFtdfDHaH3A==,type:str]
database_username: ENC[AES256_GCM,data:znz3C/RlRHFOh1YHnQiFUZVuF4DQ,iv:huKREspadUkUN869/FrtsPLtzIKDN3yaz+8QROLjmsQ=,tag:X6C4c8Hbb8M3K6oJ1rrH4g==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-13T03:23:51Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wGYPKeS091vL6N3jFgaRbpdAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTY0ZGPHFyZQDZTF2AgEQgDw2TvmKKSTSd+Qb8dj68Rb7JWsKXjnx6oKF6uJNpvkODzx1TvEeP11XhCcOCY2uOL/kZVFWToNpyJmhqZU=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-13T03:23:51Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgFz+fGqQB8waVuXypjjMcsNAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT2NTnaECJtOomL5iAgEQgDyxfxx0flq3ogLGc33Acn4dI7HI4qFXvd+C8pggV5u2CRN5olj2NFEeTLAY07kaeQFdRzakuA7lnze/hn4=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:23:52Z"
    mac: ENC[AES256_GCM,data:/+vAAc4eUIFFCPLLRqvnFL9osJjjYFXjyYT0/jvG8iwJWsAGrKG95+fAOQlNtkDtGWJMW7rwtJawj24hcZyO3whJ4KS/Gnj/Z++4EYHSpEMws4j7XO/gj6KV39+iH2oNniVtCnOZEuD0sPzu/rQMJcD5yoBypwGKGg8HZLB375Q=,iv:Dcp5+i9Yh6HDU4UwczD8FFw3HHN17KFz6Eq/lYBXzjA=,tag:J+2wwE1/DPIXUPVKUZUXKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
