database_host: ENC[AES256_GCM,data:+lJDs/En8uq2PY7qC3wTjoMMeTcGekoRog==,iv:FWydqyLFyhnnEsklJhqYTPQ1Z10g61AD68yWUMJHUrw=,tag:hwcRDHkJYbZCPhDtUvLa0A==,type:str]
database_name: ENC[AES256_GCM,data:gXwp38zKXiQPfKfWSbrGXxR7yE5s,iv:qgp2dTRZ1EIl1khNwAyrFYUep3LFjlhbEWynfg8iECs=,tag:xEWuzdxlKT+coQlyaaml0Q==,type:str]
database_password: ENC[AES256_GCM,data:dxPmSYKQXQrCV2sl3edRMQ==,iv:8E0+gc36X6usa6+bZ0QvdGY9GYZ4hfmxsgb2VzPrWzU=,tag:WjQ6B4STrxoEFtdfDHaH3A==,type:str]
database_username: ENC[AES256_GCM,data:znz3C/RlRHFOh1YHnQiFUZVuF4DQ,iv:huKREspadUkUN869/FrtsPLtzIKDN3yaz+8QROLjmsQ=,tag:X6C4c8Hbb8M3K6oJ1rrH4g==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-15T23:16:06Z"
              enc: AQICAHg/zlliNFxAWoQGTobBy1tk3DsyFSlrbUVzBXCPD0Mr2wHYlo/pRFpzwhQiSb/n0BbtAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2IWPvpXvts9ic9fMAgEQgDzG6Puti2DyJy9i6AYPgyqDUyTqgvi8MyoPgjEBKyokBWP9AWFeS9OS4JbB/BwdKbzD44cCN0ycx9TZ9gU=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-15T23:16:06Z"
              enc: AQICAHhBw6itIWtE0zgIOKJQzF+Tuue6ZZrBzruFe+12ieqHjgEpuDiLU/TkOCbniAntiY7NAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVCFDqtgogGo3caiJAgEQgDygPvFA9lTFL7JR8cbMdK9RRM/tLa4FThi+l3oFQSGL0HlHM77PzgoVs6LRHFstFo7Hv35NgxpkaEee+Tc=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VEI5NDBTSDJhSGR1STdR
                bTBPTDhPSDI0d3oyRXg3QURvWmhKYlNTNFNZCmdKNFZyQ2NiYTlqYUFHMXlYWEJ0
                dVVoSmRiN1dmaW40d3FuZ3cvM29TZHcKLS0tIG9OOGt3WXp1S1VTeTRQZHBYbTNK
                R1N4QTQ3NExIVGhJb0tTTWxCekc4MWsKrcUw4JvtM6BhQmR4Ycxrq/NuJkPRL6J4
                cvBNfsvxiAiey5irxSi6Q4nrp+9SrroQfJmxMXYNvzW0QJtxfdkmjVA=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-15T23:16:06Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA1mTlAlnuwDYAQ//a6pFMDUDGuGPwQW+YTqNY3or1MebrU8fqT9TalrJOD1j
                mxeA3o4oqK1jQEiA2qHVmumRuMB9t493qEtZwRNoRlNBu2zxiuUZUcKlRv+U5CpD
                sYwg98za/rre1xW6WsF3hhnVfinWdMMmlEdiIN098FsIWyB7Mo+L/KV4NSflHzhG
                /p9trUyNGP5ISiHiJBA4E5rDX2kZmirwR/qZnhT5k8FwOO+K2BeCv64j5rAkTNGI
                iAKquBiQ2ZRTXnwXXJzWanfkrz/HAp3XQZ9lE07cNiFo2W/MboFEIcPmktg1Q8uc
                2wlrXNHlXWxAcFEygJYa5fSmYbMZ4viNgrZeGjFQqpzfvY9f/PNI0I+aDqiYBuW1
                Z9Reo6GHq19CblhpOy6d36RBdZpRZVltkoaoIcRoLu//gS2edil6E74yTekq2x+P
                OzTNiCxxhZMVgCqCh4JHFbwFcStE3itMeA/kHDDgCkb4MOkDWyDcMNfobR8+so3z
                4MWhjGQnDF2rSe8Obo3UhOJ8XrQ2dkn5+NwKPXXbVX7AnwbIh4JM3USkXC/o2zCw
                vTJ6Jk65PD0KHOO3PvUHOWnbSXbi0KtabxOccyAWcT7w+brkaV5L6AvVHu/g1vJK
                lX2TDxxZGDSo4fpUKipaGioNCLfh5HOGdBu8QzkCQxoG9IulRoelpOaAQWfjNrfS
                XwH+N4Lmmx6EKxDxfClj3wxjrm1q29FX1fajDWTwTumf72YAuaOkX+ODb/kWKyq5
                KTRIflJFzF405G9SMo9YWNxK23RxE84acD8Ufphvt6M6Anp1aAS9u3ygQWHplHuZ
                =k0Qg
                -----END PGP MESSAGE-----
              fp: 7246137C29494AB51DB9DC75A503AED1209A6985
            - created_at: "2023-12-15T23:16:06Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ//eesE461+NQXb/4Kp1YpoNjkJFfwetgz0ZSxpOfZ5KYLA
                sivF8WGeXeBBAWxPV9bTHOD5CzNVkHKH+V7rSqBhkuD4W4ll3vYYQKjvOr1Y5jpy
                WSMpJ5NPzESFheDv7wgip1jpMOKYCU1J7alx/wDKssJSSZUwG7D1OwWralD9Cp02
                tNPAmligJV6Go5n56jZQd+uIDvKP5wuRD5cjvi39BzNx31AhrTv7duuQUiPi3qi2
                tV3ejd4nsXI5xOUzs+oqQiH6pz8xnt2jzvi/O1ayP/HAyyXajng5r2ygXqrDSpcz
                nIAnTQxGyLs6vKFWRCD/TT0MwZVUHDodND0bFT/PZMErcdxXDLCwgm7IHu3XE2d0
                eO0U8hGyFiHq93sMWInLBPuMvVZXk6gHgs4r3yvARfwW0zEjJnaH0aFz6wc9kUzm
                tJnwUjC713kFaMW+g7/0yVhoWW0iCF3IvpYApGLXK32YIa7NRnQ9P9jLqDAGYUfB
                +WfRd4q1ZUHCgogvDWa+7d1BJk6YdrNuKIXBdbWPCYilyeRQj4GOURPxe1UNc3Sf
                WE72T3p4HEoMWn3GTPetdPIqXEXstk52xPdEKOfSHctZHbRuvzW4afJ8nqAoc0Jx
                PMIvxOjdkdaBoWnfj/lQ5V4PclEVsEuhQ3wSU1MQernM+/zKAcVHa0nZaf3EqF/S
                XwGOJwe5wcwy0+Ne6r7cOHjbsACzpugVnRom5hv92w3+X/YNcghShuj1PiLMjmOx
                sUP8fUSHYYKw1qgif9C4Hq98YVRi2piN5Iu9fPrUJZg8YhothWk7mbZKqv55d1BL
                =FxUx
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T03:23:52Z"
    mac: ENC[AES256_GCM,data:/+vAAc4eUIFFCPLLRqvnFL9osJjjYFXjyYT0/jvG8iwJWsAGrKG95+fAOQlNtkDtGWJMW7rwtJawj24hcZyO3whJ4KS/Gnj/Z++4EYHSpEMws4j7XO/gj6KV39+iH2oNniVtCnOZEuD0sPzu/rQMJcD5yoBypwGKGg8HZLB375Q=,iv:Dcp5+i9Yh6HDU4UwczD8FFw3HHN17KFz6Eq/lYBXzjA=,tag:J+2wwE1/DPIXUPVKUZUXKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
