database_host: ENC[AES256_GCM,data:SwcfRSTTnsh1vjDFx1iN1q1HX1NXWUlhGt8=,iv:e6CZWwhR9FA4Zo3fXdCyijIRWkMwiwmJnYzBVN3i5W4=,tag:xSDD0iG9Ux443LWBz1b5hg==,type:str]
database_name: ENC[AES256_GCM,data:dHucZPRLykWAfwL0W2uHCpzKMBjp+ZMzTQ==,iv:FU767JBphEvWKsdBQa40xRd0ZUHmmcfrkSkQ2Ez1kTA=,tag:reKIeTyJ+xiDk7xnzHIksg==,type:str]
database_password: ENC[AES256_GCM,data:fnqlnSQ+HeWHUH9crN0aecxvKhNzSTADF1/tazKdeJY=,iv:bfAE8EXEtrWpjCulBP7FtAe1BIMSNkuCRXEiNww04Gw=,tag:jWCykESJmfKQ5aj+QiHLGQ==,type:str]
database_username: ENC[AES256_GCM,data:BCrwY91txXgCzyy0OkI3NXNgNjxF/uacBMSIofQP9w==,iv:K2B3226khaTc1S6WAOX36wdJnvMu1JsSPAHjeDGGXhw=,tag:S5bW7lp8fmOrBR3DgoaKoA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-19T04:13:52Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgFwz0PrzAlMYKAPMLabDruqAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9CxKgRysb1mJba77AgEQgDyCy4zNVSkfkmgIGM4wh+vrlpY6BsneEfZHHYzRlR4N/Pr6U07NEJstXliadnBnnOKXTpuoq1D+/L0bh9Y=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-19T04:13:52Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAFUcz1t5EaCfl43soVZH7MsAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbWdfHXDBQ/56UYV1AgEQgDx7R95oMpcyXhFuxcQHAHPItpP31HSIVHKfV7bFVDDBKw8dHXsKK0tnzrfECz4tSRPeKrhKh8u20kv/PcM=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbkhOOGJJdFQyeDNHMHRN
                bnNpUVhZeGFhVGxQNG53cjkwb3VkMStlblZzCmhOSFRuU05LeWdtMWNzaTdqVk5l
                dG1YVEVXTVBTVDhHaDVVMGFsRzNVc0UKLS0tIFpSZmtrRlVtbGFOMDJTM0N2VTZu
                UHVTdEpsVHdXbXJDZ0wxN3hzeloyeEkK2O+MFGDmVd4WmK1LyE5QMbozOhPBrwyj
                5XNoKY3fBDbbLupvag8l+tsGb0bu8CtaZaIN0aavHtCHJ0tsw8Sa+Wg=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-19T04:13:52Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA29+HcNgvVD7ARAAw1uEP5/CI5+8szxKBLQJ8krxzA++QFtkEpeeOVtUbrZC
                ln5yq8QmRlc7SLGTNwUxzMBAHIQN7GFAMiUccYLn6fkKWk2JomnE37wSWkxdNY3e
                X7+SlNdxbFX8GOnjVu+04yD7lvXYP+OMGnmn7HrPKw8IC55mXghVvXRJdDA/gZcf
                446tV+gnkF69u63CBgNcgtFU6webd4hSvKelVVD0fytU2kFQsbP3jkrquAjwgsV2
                xoTMtuTCBumRPtnzLtOH2MTQVcOnMpZLR693dn7hbEF4kzRkGv5xID/wkfCq6cvl
                1BXuInx0PmXRpEuawRS21A4+Vax+73D7pK9fLiiVCBO8FUEJqJXUFQyOOENA//dD
                dI4/Y8HfOoLwu5VMlIM7VQdbMSa0G9pNLCUuYL+qYDoJ84TNo+Wme6xXXrDI+unT
                UKv4v+lW3viyKZcnYKcmzKIHIW1+IzE6BN6l0WBtzmsqAeg1L98in9/h5MTrTmZP
                zut3rdHaifY6sYxR4GcpdgxiHhaVpMSNuipjEXNPCo1YnmvcyzfmhAwBGwrxa0JE
                XAuAAkVM3Rlqy8dDYRgoRZC2GAxGc4RFnt0z455MlJLrPpJA868NIegwK3IoHW6C
                bi46aEJtuzZ4aCdRAshjI24iq6j+YPBtUMwKJnOkglh3GvXgzN4JSyHy26hifb/S
                XwFY0ZaPnKe97Oxu4Sq6Yx0IUUBjgKuj6pvCjx0dTDesVtO5e2ibSbP79m0ZN7lV
                JS4Ed/FkZ6k9kdGzjmvSiMr0ONHTOZX8kC2tegRI5JI+JjzoDZtE2RywFmd8pvM2
                =CRRy
                -----END PGP MESSAGE-----
              fp: 9BC1204B386DC64785CDFDF35AD58514798366A8
            - created_at: "2023-12-19T04:13:52Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ//RotbKrRvgMfCrsMon3Ax8xpFpwP6cMlj8I3HcDJecJvo
                VFPcJlj1xHrLtdEvzx499vLROPAq6wuOYaLisG5hHvNHNIumdkwab39TWi1iN/ha
                oI5Gf6NLUATcecmyac0wxdtgPSJVdV9TmxGO2krkVZ3HaZ/ZuhJdNBb7moIpUuVO
                KpUfCEHZKvPpPL13IjQVIq1P4eKgA/2VChUSGlcYBVn1JC0fu3AW7ErgK5OxHbT3
                bu4uAnhrURLfp8i3K9ta6bW7gcn4m5M1bpfvzYG1YwLVkUR8Nat7DtPqQwF7Ex6p
                EEMDC2g5EYXtV/0ByWNaffdeOCz+9FHf84ku97ReYBubjEBjvLuTo65DX+1JI1YK
                vMxs/HIN/iZ28STFDvQGutXaYp6ZinFQNX5aRJm6mcZIHaFoVUF3LRYWZoYRDLOH
                d6GgWVP7skZyboCPwhkbrMYPE1kBlKkAW4QXWCxOC2U64HRG6AdcZohyMIarjR+8
                Kt/WzVS04q5terYLbrtjjJmjjw5HTtuwl9zfKW2WliOhkoCc0TKlgvZj5zD3zB2Y
                BbhouuStz1JnAf90K7HIygeKEdzNxJ8y5lS/D20Y6k7hmk8cFV/T3QXqTxCcVu3d
                QgTApkGx92hCuutAvleqWHK1XN3atoP6KX8GKaRC2oNZa7gtCI+1DYluntqUOWPS
                XwF0mz8NRRVw0avqFkbjAQhUh6lnU0LosZsWVUeenXzkwSinYRSwVKdDVj4QMOQ4
                dozHcR46TAHtCt2tCvqHKhJikHYUib7vRSv3B1lZfa1Z1QqCRdvwasMIn21o/mCQ
                =vWdN
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T09:03:03Z"
    mac: ENC[AES256_GCM,data:SfJzWe+4K5yuIx4Z/DLxGdMvqaVlSwN8cdQdrhD8RaOc6Sgi2ociKONA3PyeLLEIxEmMBi/GmnlubnHcHGy7Z6fnAMqzZTrcMrSu8DRi3vGoBwdLYCUa4Sy8MAHKjP4ne9IFLVMZqfn9BGRK6BHZEbKwi5ZBjdOCo4Z50kW1UXY=,iv:9CNzt42sg0SSggzfOaZG78DBBqy/9h3gx3aqmHbg2L8=,tag:iWxLm55AFP5Iz2ohuRoGYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
