bugsnagAPIKey: ENC[AES256_GCM,data:XLgZSXXOWmeFPsayWr8ahE2LCpsdZlB7YnOG6+IMwEI=,iv:MEB8lx6xFakgDlf4QLbsk+dEtdMbs3Sb07F+8FPmUDM=,tag:Km0Ue0XUrHLOknUPxyQquA==,type:str]
database_host: ENC[AES256_GCM,data:27QBHyOQlRyIHSpq0d3NoGatOa9gy9wu6nqW065q7iMt0rvaDMNb33I=,iv:j0lIr5Qf0U8rdvrGNXAcoRPPpJYWcEOT2qeShYFFVPw=,tag:mkxNJIYbczjf/4xI0/6CEQ==,type:str]
database_name: ENC[AES256_GCM,data:B9xNtDzNQgD2yg8glHjbJ9nxWyr01g==,iv:DkiAPB8N7nscjrRsJpomry3gs3hg9PRWGk/y1YA2xJg=,tag:0juRWkUFb7mwghnBUQr6kQ==,type:str]
database_password: ENC[AES256_GCM,data:IHbfU0FrxJPPPxuWpggE2JUwiz4=,iv:4GNRQTOO+8T8PnU9etiVujzio0+2KnrO5opSZbg7bYQ=,tag:GLvKzoEyjZPG6IU46q41WA==,type:str]
database_username: ENC[AES256_GCM,data:TJzbRGMZCmpC8BUW+T+4fa2OfaA=,iv:Jb5ue7CdqICSaLWgolg6AySRNtxuAxouGbxAuEItCWM=,tag:cVQpwh9RO5GIZ6GRoyAu1g==,type:str]
environment: ENC[AES256_GCM,data:YF934NPCE8KA3g==,iv:oaSOuDwstyXofZsm8/3xYY7gDg5Lrwi+zkoWkCGeLS4=,tag:q5KfMLy1vClXpbBO/GNxIQ==,type:str]
newRelicKey: ENC[AES256_GCM,data:33ZGG4JqO+5HFqJkAPcU2RYlpdXZYYEKgB43pipJX9eGQpoNIgVy/w==,iv:TZP+TyQJf9yo9ag/T9lHbc7W7KWMR5j/phHHwPj9KK8=,tag:YNfuOD41W2GSeYsxKCRpcw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-19T04:14:27Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgGE6Ebm5cbFpH/icHbCbR4WAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMk7bu2dnG35m8F+iEAgEQgDxR8nEaqJtshW2pVjFY85pEZ441g/T2M8fvMqEr1eguEMB9Wtes08dHbLuhUztbquQHgGXkvzPNEp4K1dw=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-19T04:14:27Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAGP0YlwFx1oKDbpbswdhLrIAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMWXqxCGvQZTk/xi//AgEQgDxSfdG9xhDBIG6XJIEvT+wEsgcDwmsjXYpiBJKF6mmuhZk0NJIR1feDOfEPKAJPDt52PX6asdVk+qHXWVA=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa3FZVmJuN2t0WmlxT1F1
                aWJkN1owZzdncDdVUjlSRCtsQ1Z3aGtwSFY0CnluQ3pwbVdYa1pKUGJzV2lnQkVp
                VlhPOHovUXlpdWhGREI2TlRuRXVKcXMKLS0tIHkvVmlCc3ZYelIzS1RMbkVxNGJw
                ZzdPVTgrMnFHdXdyYTF4bjcvOWxubTAK9eVW/CUpYbNIiC0yQfiCN1ZU1c5qss0P
                dbrlGaJ4re6uf+ieqNu7vfR+JdX4tzy1kdRjb73drnemkSRWgGnaxr8=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-19T04:14:27Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA29+HcNgvVD7AQ//XcI7aiBAzZq0x+Fi99FdsRRe3vfnNwYcaYBpsVsaWV3S
                dwKGmMd2kqjj7eSb5so31OX+Mn5/Qw+EVEK0H32gLaSEY8iLPZmqOUbhZoiNtksY
                Cx4+PpTzYg6Uq2cOABWJD2btL4tZ8JoMVzZbNwH84ysVUV1lAx5zxH+vvhnT4Y60
                FL8eCydJxbV9bofyC450vU430S3KKWio7INc+UiAJT/Id11DxOFl5foOl2gpJC3S
                44jwZKdJZPAfebcR8urQnRppCG51lVVrAST8fMmyTagfQ1lKb6+Mrc4QDQyMJVyr
                NEXxtEzPukMxJwCzko9FgZiiNJcIBut4UstUplQIRKFlC9jjvrWn93YABamGEVv9
                mgccUTxYUHFGUctId+uPzGMEyV+g/j7dquA+D0z6NeywLYlGLawK79zQkRtbVKGx
                SQDuj3xt/TVUuA7eb9EM5TQtlIAXEIJitjOjajfbrUOq+nloRvYe1sbef5BpjIrx
                fWTGZN8CoIbBsEaQvy4CXEgRG1zCbaWzObJVNTCW072mnUvzj5dv2J51LmdXG7fY
                lpYIKy/xIM9jnqsuleirzGEsvMTq9EXDkLKkyr0/Hgt231XsIBaA2TxG4twM1wHc
                IG7Okhvxs9vqQV4V1CVLjKkASQ54DmMS6xgubJf+ez0DkjrZ5gMd8lo09yLcO6XS
                XwGSzOaMlQxpn/7X6PH483vM3DQ/hDP2UqtKZcItGGnu3faJqQ8evrVdVoj+whld
                VAEBedtDTBEZWgfZUpJmchLnKk/2rZotyG1Zy4GN0cS6SNaLlwfZgGs+zahtHsRv
                =NF09
                -----END PGP MESSAGE-----
              fp: 9BC1204B386DC64785CDFDF35AD58514798366A8
            - created_at: "2023-12-19T04:14:27Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ//SOC5MAny6ocYJeCV+PcXmu5Wv3tNoP/faGuZAKOnKPWu
                JDGo4EpKPBPhYLrIr5/lHT7034sKVQLC4v2lMIs6KepARSIG+g+25CdRIpNVLayE
                Peujysj/F8V53ob7PVwl9XKqOZAxBb+gcmcUS6S/XwrNM+5l/dJJExVPVgRIHG2O
                2uav9ND+WF5F6D3MDnO5pzifjsWK78l/lAGpTQA+2l6ZjQcj6RL+144VhMvOX/kr
                WvkmO8WTwIvGMqr7lHemd3CAa2AIiaBCYI2zHoXUzoV44AqkfwwkW+6IaoxeQAgB
                hbbZHKb7YT/F71MqRUfZeXQBckhY3+CiD7NU1iY6IBrMyrpp+T7LiKG6FjiBPi0K
                BthfCjxIs17jmAuP41WQaMd67Qv5R8xN26qt/gIMd1SnvPUHNrDg5DDAjbGXFvuU
                +B2rpjB+k7bCy0TwJzQV7bxQ+35LudM0P6OfS7lTmBNOau0fkzyUt15I0ZWUD5ZE
                M7d1SlVN6r0bmtZJC4qvYsksg73cLMGUMiqd4Pkf54bFn0LHGq3RE8zYpDd3hWFv
                1cYw0ocnY30vGn7trUeBIXwxtEWo8+YuARTCRTC3y1ujvQFFoVSIqs+FXvW3E80N
                FjqDCiTEyVhYID1pPpZu9In2/4AZ7VCjN6d1QXCBF7WdAKwEAvCUsGrTKa3r1wXS
                XwF8TKpsK/TqkO8kiSIFRR0C/NocxgyDBOYRy4VooS6Y+ZxOEHocHjH9tt57meV2
                ijit6cxV+tTGw/YzZMcRRdMpGc+cYpjGc+OTSAHtdto9BdUMQzKQqSRiDW1u0cBF
                =oKag
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T09:03:32Z"
    mac: ENC[AES256_GCM,data:AStbjVagVOOiapzHd5Mnz5wss1qt7nWgI1xDjgXpu+2KxbBYXGvzOhjAHppXvPmZg1phIQrrqSB6S42F+dlcrHmtYWNJ2ZMXV2cbOegW/yVtbM0uLrJ4kaYGWm22DT5qNpMdmddiyx6bYWXewQvmkm8vO1hTiSFKArY/WxPfio4=,iv:kPKy56wTbr4Qp7sIOVBeIIUs7qChnzZAKK04Y1GGV0s=,tag:WiOrjjtEa3bmHdyQAm/CkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
