bugsnagAPIKey: ENC[AES256_GCM,data:XLgZSXXOWmeFPsayWr8ahE2LCpsdZlB7YnOG6+IMwEI=,iv:MEB8lx6xFakgDlf4QLbsk+dEtdMbs3Sb07F+8FPmUDM=,tag:Km0Ue0XUrHLOknUPxyQquA==,type:str]
database_host: ENC[AES256_GCM,data:27QBHyOQlRyIHSpq0d3NoGatOa9gy9wu6nqW065q7iMt0rvaDMNb33I=,iv:j0lIr5Qf0U8rdvrGNXAcoRPPpJYWcEOT2qeShYFFVPw=,tag:mkxNJIYbczjf/4xI0/6CEQ==,type:str]
database_name: ENC[AES256_GCM,data:B9xNtDzNQgD2yg8glHjbJ9nxWyr01g==,iv:DkiAPB8N7nscjrRsJpomry3gs3hg9PRWGk/y1YA2xJg=,tag:0juRWkUFb7mwghnBUQr6kQ==,type:str]
database_password: ENC[AES256_GCM,data:IHbfU0FrxJPPPxuWpggE2JUwiz4=,iv:4GNRQTOO+8T8PnU9etiVujzio0+2KnrO5opSZbg7bYQ=,tag:GLvKzoEyjZPG6IU46q41WA==,type:str]
database_username: ENC[AES256_GCM,data:TJzbRGMZCmpC8BUW+T+4fa2OfaA=,iv:Jb5ue7CdqICSaLWgolg6AySRNtxuAxouGbxAuEItCWM=,tag:cVQpwh9RO5GIZ6GRoyAu1g==,type:str]
environment: ENC[AES256_GCM,data:YF934NPCE8KA3g==,iv:oaSOuDwstyXofZsm8/3xYY7gDg5Lrwi+zkoWkCGeLS4=,tag:q5KfMLy1vClXpbBO/GNxIQ==,type:str]
newRelicKey: ENC[AES256_GCM,data:33ZGG4JqO+5HFqJkAPcU2RYlpdXZYYEKgB43pipJX9eGQpoNIgVy/w==,iv:TZP+TyQJf9yo9ag/T9lHbc7W7KWMR5j/phHHwPj9KK8=,tag:YNfuOD41W2GSeYsxKCRpcw==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-14T09:03:32Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgFtYIxRq1BhqkgZEo9Ty3hmAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4Hg7wd4xdylPGAFaAgEQgDyx5l1P0tQZxWPP4ctYjN1f7w/UMDJ9dcsRc9tt+FzIMdhPZlpIwotN0TaRMmU/+HWRl9+tb7X0ewfFIK0=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-14T09:03:32Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAEtgx4r66XEUg/tvXeUSHMtAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBKOw6fHTfJriYJmyAgEQgDy13O0uNRjqiBhNwSolOTOgkwDgO8waiYiqAEnQl9M4ShR+HePlCnvGCSRiDJBdFV5dJYwTc7v2e/KEP7U=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T09:03:32Z"
    mac: ENC[AES256_GCM,data:AStbjVagVOOiapzHd5Mnz5wss1qt7nWgI1xDjgXpu+2KxbBYXGvzOhjAHppXvPmZg1phIQrrqSB6S42F+dlcrHmtYWNJ2ZMXV2cbOegW/yVtbM0uLrJ4kaYGWm22DT5qNpMdmddiyx6bYWXewQvmkm8vO1hTiSFKArY/WxPfio4=,iv:kPKy56wTbr4Qp7sIOVBeIIUs7qChnzZAKK04Y1GGV0s=,tag:WiOrjjtEa3bmHdyQAm/CkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
