environment: ENC[AES256_GCM,data:wjY/Ii4uxmOBCA==,iv:aoac5A6BLiHQ9fYDz/ttRm3wRAXpe6qa+L3lmrTuqLw=,tag:/cw1j83CJLnL6xI6wo8BSw==,type:str]
newRelicKey: ENC[AES256_GCM,data:Swr+j4LxQ7dyp7tmtKBLu0bdLRGrB4eQyD5N6phQmR/DFNYXMB2RIg==,iv:Z4uR0ePpQlWhhfm4e1dc1zX9t8v6zct2yeXOO9ZBmKw=,tag:z2Emxf1JyclnsClCBJbguA==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-14T09:03:36Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgEFd0U+Hn7ZTtMMbD5CgadCAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMc4m3quJ+VGk7CeX6AgEQgDxsc+qbFdqgsDa5GRlrPVqrEziT3Fy6QyN8EWQVtkriAN59EiAFVVwkoRMkDcbl3n/cJBnuTmJHM+7cnk4=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-14T09:03:36Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAFUZnG5ordW2tRpp/8VYt1kAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7s8P57a8VSwZUkyPAgEQgDy3vHa6Z4BF+mGEE4ZAs1JjslZxU/qRkq7CohOiKiqy8sa9jPhAS26ina1igGAA7cvqzZjK9HByiyBavAg=
              aws_profile: ""
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T09:03:37Z"
    mac: ENC[AES256_GCM,data:q/OIRDU9cun1GBq93rasE1HP237tAqVKhW0PRPPf2Cx0mv+l1V2v9Ad9yE0Ghlzkx376yg7YaLrcNe4SkHSZqi20c02a0FLMDmODGq36pck293+8aJ0c3mU8HgLerNVg6pDqMoYVzhV0NTZjX04dAK0hKy7hJ27zgybjCAvAxa8=,iv:nudfhyXg4tEIiIm8dHnzDmi37oD59jacHHExvA7cnXQ=,tag:JMa+sg8Kz95RVt1h7u3GwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
