database_host: ENC[AES256_GCM,data:h2NjEkN9EadI4tmstO5269j1sS0pdFmi47w=,iv:FKSTC/pRvOLRV9hDvHSz/poLxOHAvzIOpklEBNCCwik=,tag:BZH0e/8q473frEpfGKgqtw==,type:str]
database_name: ENC[AES256_GCM,data:SxLWnOCsmTl6m1MI+LM+3LNq1yu5E3eF,iv:DbboHe7usemIY63HE1ek8p0eIzd413yajkRgdthlDuw=,tag:CJP6tMBKPGKY2cZDjHuA9A==,type:str]
database_password: ENC[AES256_GCM,data:oRRmJ8XaPwVN6D2RHKYKrA==,iv:glYqcvZksbtwn9OqYTHEfdhkDB6a/P5dQo0k1nNww08=,tag:IJEqzSH+ffszlZgvZ7JJ4A==,type:str]
database_username: ENC[AES256_GCM,data:HhhSZupRHGuEP8sfFj3eDn9SsNU4FMJe,iv:tuseYUjo/7MSC6zhVQCgJALjpE0R++TxmwomivxKQyI=,tag:A7ppRsUn40yPlt6WqtDX9Q==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - kms:
            - arn: arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7
              context:
                account: sops-sa
                region: us-east-1
                type: kms-master-key
              created_at: "2023-12-19T04:14:42Z"
              enc: AQICAHgMQtzNqT9Xo559iaM8skvkGg0pX65sB25tm/Vusf/uXgGAMBuIeaKsXcLoVSNLEaGCAAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj90ad2BTpkPqvCJlAgEQgDxw7VHnDmV3rT3S5t6ntXDtoJheIXMK8ByfgKmjI4tNpxFqDm7FCDkBKQw5l+POsKhm5dSHJEN6926iFwU=
              aws_profile: ""
          hc_vault: []
          age: []
        - kms:
            - arn: arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31
              context:
                account: sops-sa
                region: us-west-2
                type: kms-master-key
              created_at: "2023-12-19T04:14:42Z"
              enc: AQICAHhcYMh2txqTF/dAueGzggShw3+LZmxAq90VueJF4+7uKAERSgwDPTH6DPlpzYyklyl7AAAAfzB9BgkqhkiG9w0BBwagcDBuAgEAMGkGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQfbcx4y/qkzK4ANhAgEQgDyJWsb2SzrNw4G5DiSu+5uBa9ubJvkA8t1uYTGMLQS3KTXhJ3qqKSX1rmixaoW7s+pVZ54e4CVtlU0bMbo=
              aws_profile: ""
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ0RzSmR3Tk5WYVNZRXpW
                amIwTEs2TVhMZUg5TkpaNVE0cTB4UWpqanlNCk9ZRk84UEZIN0wya00wU2RlTVhM
                dXEwY3o2MTloTkdVQVVHSUNtRldaaDQKLS0tIHFhYSsrN0RFZ1Mza1BHanpzMVNh
                TldRZG5zSEpkOHMrVmhYdDFSeWhmNGMKa0rDBJIWsPFdAF4ho4LXRrRweQpcxIN4
                HZH4zoU0kkFD7/iU1XsSBxKhmj7PMBl8+8aBSdWKXAsyjR8UTBosqNM=
                -----END AGE ENCRYPTED FILE-----
        - pgp:
            - created_at: "2023-12-19T04:14:42Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA29+HcNgvVD7AQ//Zpcim+2QNAwQCrikmSAfeFo/nM3A+jgJjMqvo7wKigcl
                o3V3TeChH/X+Ot7gUXhbIZapqgVJxqaIB7Db/Ns0R3imTFebYEvqX1nruWUxb2/c
                S21JijdWmfz8SlghHAV5Ue9Kid35VXjvEa9okJ6CBVBzA3O4JR9HB7h4hbcC0xGB
                blQ7C79JDTnLHEeXsFJf6YOYbj7lF0iH/95Xxo/Ow3neIzccaJDUDepbvP1xvYJ1
                tNDDpefzXwLjL/SDTSb9IqgpikefTe0qIQRxlSamSOtx8n4vyAzx1MAPUoPpfY9P
                76hBH0xJ4QBaAc91M9NtDluRoeLfwFC8XNU3RRES+ZS1f6Q4ux18VKlw2hbnyg9t
                T/XYfX1TJ6s0bEnt6CQkbSKBFRyyhDnX55bEGAz1yxVhNKR4/6jGnWYO+w1yBxLC
                ef0sEAl8/YoIp2de/CBSta3Ago2vlCKGJjnmYMApncBESeunaDgEjuLVMK3YiaLP
                6+5YkI3/S9eWE+11+CBIIj1ZnqmsndoLRL+TVGcZ99DGIh14SDvnfXLcR/UwaStw
                vrQLYweLcF88EbvDoLd0JqdwnaDQTTM8pUyj25PjNZcHlPsvXuJQ575I8X1oDDXe
                QZDDuBYeF+s7lIzQJpRAgovkhOaf3Nb6Ht63MDagXGotnD+ekZyjUv9ObkEXVknS
                XwEAQm/wIw+iEDhDl23QWmdWUgAbuw7+tvgusDTKLdiBgbCVYbD0WZW8bdAVDu5v
                JPXqaun/WZfGrRVmC6zWa8TSMi2UM5Kx0q0tphsYfuXYdfJBVWO5EI+2sK//2/dn
                =dVVb
                -----END PGP MESSAGE-----
              fp: 9BC1204B386DC64785CDFDF35AD58514798366A8
            - created_at: "2023-12-19T04:14:42Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hQIMA+OWQrJ9b8nlAQ//TUwcylc1hqBVWsPpdif74tliUVaoVWg7VUu/dL7d4lNI
                H97GwBqrkaiBf8zWn180IWYSn1gP/N1t/r4ZLYA47wsF//w0bjmNYaCqzlVXucxb
                wpwsDT4tAp15ASVf1XQskgEzHnFr5C38wGqieG4Kk8XZ46U+bc3gszewuHKGqfrZ
                cL7+hvWlgitdPPd88xkI7wBe4YY/y2Oo/1wy4+q0DDPQuvBLH16HsKQ7tL6JKbjn
                MbQJTY6kDwTcmfWvNAskYSKUuu8QAZiO+XKEfYKwuBDUxsf0RR8jTfMOWN0Feu7W
                WO2WhKQ1PD0PpE4ZfjxMRhrmM68PwKlqoM2KFRqU5+zpKVOGsVP81AqzjvgT2fnP
                InjnfghydP48FY6QgHWEQR3Had+nEE6lxgv2pY/4gAOwmTay00xSQnxVtBnYv/Au
                u32Ei+lOgTgYLDl/C9L2CdCulTJ0F5Xt7YPn3qRdy0RCQF3JQcWMPmsl/3NZOElI
                9GWqeAFPO4DxewWdL1TM24/z/1FteBTD73C+XWPhXkjjzcM7LqTqRVVD06WkpNDI
                4O/xxP9Pltr4M7pz80Q81TuWKbFjtoLHfQAnnzJT3MXWBmyWFWUueXBYszyf9sBX
                1e8jPrjOSWScYYWmLGXs7IhmPb9Z4ss6hmOiTdHQmfss0vjxI3s83FS7qqP+R6LS
                XwGE1i6Lwq/40ik4kMXHE4jMGUGVXhM4qm66gW6rqcInUUJCMVxVTvgcigglss8v
                Mn7pi7mND/bWSjnkK8ByMKQj1R6BLIbh03aftmLx2kGVz6N0F+7GhEcGPWxYY5PH
                =vETh
                -----END PGP MESSAGE-----
              fp: 7EFF431796D90A32826B4C84178F957C4F712CA5
          hc_vault: []
          age: []
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T09:03:45Z"
    mac: ENC[AES256_GCM,data:hqaDv5fGMfAWrY0n3ShJEUSW4PH1D/7jCnY21L2gws4Aw/AKUn00ISPxWVtFphZqB2hmO+gEnqLroe9jQki0F2R7BavqpEiYwXrRQnZT6iaPXLFhaRD3qsS3hbtQn0VMs8qNJjC3ZmGlGRj76ArJJpJwuMTkNP7m3yWw85Jo7qI=,iv:kj95je3/E0vu5vJypD6UNIgSrgFipawdWtt18gV4BwU=,tag:W/CbGSaL6iROOJEjNSiSIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
