destination_rules:
# infra - v2
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/sandbox/infra/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/staging/infra/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2/" # default
    vault_kv_version: 2 # default
    path_regex: secrets/production/infra/*
    omit_extensions: true

# customer-experience - v2
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/sandbox/customer-experience/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/staging/customer-experience/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/production/customer-experience/*
    omit_extensions: true

# lending - v2
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/sandbox/lending/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/staging/lending/*
    omit_extensions: true
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/production/lending/*
    omit_extensions: true

# sandbox
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/sandbox/*/*
    omit_extensions: true
# staging
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/staging/*/*
    omit_extensions: true
# production
  - vault_path: "/"
    vault_kv_mount_name: "secret-v2" # default
    vault_kv_version: 2 # default
    path_regex: secrets/production/*/*
    omit_extensions: true

# Secret Keys #
creation_rules:
# path: /secrets
# sandbox
  - path_regex: secrets/sandbox/customer-experience/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
      #   context:
      #     account: vault-sa
      #     region: us-east-1
      #     type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
      #   context:
      #     account: vault-sa
      #     region: us-west-2
      #     type: kms-master-key
    #customer-experience
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - 'FBBDA26E7AE5023C66D98453A93F3127586BD012'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/sandbox/infra/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
      #   context:
      #     account: vault-sa
      #     region: us-east-1
      #     type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
      #   context:
      #     account: vault-sa
      #     region: us-west-2
      #     type: kms-master-key
    #infra
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - 'FBBDA26E7AE5023C66D98453A93F3127586BD012'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/sandbox/lending/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
      #   context:
      #     account: vault-sa
      #     region: us-east-1
      #     type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
      # - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
      #   context:
      #     account: vault-sa
      #     region: us-west-2
      #     type: kms-master-key
    #lending
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - 'FBBDA26E7AE5023C66D98453A93F3127586BD012'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'

# staging
  - path_regex: secrets/staging/customer-experience/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #customer-experience
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '7246137C29494AB51DB9DC75A503AED1209A6985'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/staging/infra/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #infra
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '7246137C29494AB51DB9DC75A503AED1209A6985'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/staging/lending/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #lending
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '7246137C29494AB51DB9DC75A503AED1209A6985'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/staging/*/.*\.(yml|yaml)$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:831351477977:key/206ebfec-4f97-4c3a-8439-92869a2f24df'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:831351477977:key/7c3f81d7-1acc-474c-809b-dd9f8d9fe479'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #lending
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '7246137C29494AB51DB9DC75A503AED1209A6985'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'

# production
  - path_regex: secrets/production/customer-experience/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #customer-experience
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '9BC1204B386DC64785CDFDF35AD58514798366A8'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/production/infra/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #infra
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '9BC1204B386DC64785CDFDF35AD58514798366A8'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'
  - path_regex: secrets/production/lending/.*\.yaml$
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:075440130607:key/9c9d8098-b5bd-49aa-a778-b5ed3bf39be7'
        context:
          account: sops-sa
          region: us-east-1
          type: kms-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:075440130607:key/89541f0d-dcd8-4b30-916e-287ede732d31'
        context:
          account: sops-sa
          region: us-west-2
          type: kms-master-key
    #lending
    - age:
        - 'age1uehup3jrcx5dlar4q8p8vw57d4lwkc2hcdtkmqhcrdp0n6lhvyas05ruf2'
    - pgp:
        - '9BC1204B386DC64785CDFDF35AD58514798366A8'
        - '7EFF431796D90A32826B4C84178F957C4F712CA5'

# path: /age-keys
  - path_regex: age-keys/infra/.*\.txt$
    unencrypted-suffix: '^(AGE-SECRET-KEY-*)$'
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
        context:
          account: default
          type: age-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
        context:
          account: default
          type: age-master-key
  - path_regex: age-keys/lending/.*\.txt$
    unencrypted-suffix: '^(AGE-SECRET-KEY-*)$'
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
        context:
          account: default
          type: age-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
        context:
          account: default
          type: age-master-key
  - path_regex: age-keys/customer-experience/.*\.txt$
    unencrypted-suffix: '^(AGE-SECRET-KEY-*)$'
    shamir_threshold: 2 # master keys from two of the three different key groups in order to decrypt the file
    key_groups:
    #default
    - kms:
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/9d11b3d7-3b7c-4cde-ad6a-75a2721e0e27'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-east-1:644712362974:key/978a683a-4864-4537-88fb-2dc8ea4f8080'
        context:
          account: default
          type: age-master-key
    - kms:
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/9d994675-3143-4b2a-a920-459c87207998'
        context:
          account: sops-sa
          type: age-master-key
      - arn: 'arn:aws:kms:us-west-2:644712362974:key/5dcee9a6-72f1-4a7f-bdfe-f7be9ad02b72'
        context:
          account: default
          type: age-master-key