name: Create or Update Secret

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - production
          - staging
          - sandbox
      secret_category:
        description: 'Select Secret Category'
        required: true
        type: choice
        options:
          - customer-experience
          - infra
          - lending
      service:
        description: 'Name of the service (secret file name without extension)'
        required: true
      secret_key:
        description: 'Secret key to add or update'
        required: true
      secret_value:
        description: 'Secret value for the key'
        required: true
      sops_version:
        description: 'SOPS configuration version (v1 or v2)'
        required: true
        type: choice
        options:
          - v1
          - v2

jobs:
  add-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
          sudo dpkg -i sops_3.7.1_amd64.deb

      # Define the secret file path
      - name: Define Secret File Path
        run: |
          echo "SECRET_FILE_PATH=secrets/${{ github.event.inputs.environment }}/${{ github.event.inputs.secret_category }}/${{ github.event.inputs.service }}.yaml" >> $GITHUB_ENV

      # Check if the secret file exists
      - name: Check if Secret File Exists
        run: |
          if [ ! -f "${{ env.SECRET_FILE_PATH }}" ]; then
            echo "::error ::Secret file does not exist or path is incorrect."
            exit 1
          fi

      # Decrypt the secret file
      - name: Decrypt Secret File
        run: |
          sops --config configs/${{ github.event.inputs.sops_version }}_sops.yaml --decrypt ${{ env.SECRET_FILE_PATH }} > decrypted_file.yml

      # Add or update the secret using the hmanzur action
      - name: Add or Update Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: ${{ github.event.inputs.secret_key }}
          value: ${{ github.event.inputs.secret_value }}
          repository: thinkinfra/infra-secrets
          token: ${{ secrets.GITHUB_TOKEN }}

      # Re-encrypt the secret file
      - name: Re-Encrypt Secret File
        run: |
          sops --encrypt decrypted_file.yml > ${{ env.SECRET_FILE_PATH }}

      # # Commit changes to the repository
      # - name: Commit changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add ${{ env.SECRET_FILE_PATH }}
      #     git commit -m "Update secrets"
      #     git push
