name: Running code review via Reviewdog

on:
  # push:
  #   branches:
  #   - "main"
  #   - "gh-action/workflow/INF-9277"
  workflow_dispatch:
    # pull_request:
      #   branches: [ "main" ]
      # schedule:
        #   - cron: "0 4 * * *" # run once a day at 4 AM
  # workflow_run:
  #   workflows: ["Main Workflow"]
  #   branches: [main]
  #   types:
  #     - completed
  #     - requested

jobs:
  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-gitleaks@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: gitleaks-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning